### ISSUE TITLE
What this is all about

### ISSUE THREAD

**Issue by glueckpress** [deworg/p2-rosetta#1]
_[Got it!](https://github.com/deworg/p2-rosetta/issues/1#issuecomment-59207013)_ :)
## This is what we have.

![deworg-is-small](https://cloud.githubusercontent.com/assets/308422/4529777/247962de-4d7a-11e4-8809-310a15f66c06.png)
## This is what make/org has.

![makeorg-is-small](https://cloud.githubusercontent.com/assets/308422/4529785/34cc89cc-4d7a-11e4-9d6a-407bc5676217.png)
## This is what we want … sort of.

![deworg-should](https://cloud.githubusercontent.com/assets/308422/4529792/4bfd6062-4d7a-11e4-9ecd-c3a2f8dac8eb.png)

**…and responsive.**
## Ressources
- [WordPress.org Meta Handbook](https://make.wordpress.org/meta/handbook/projects/global-wordpress-org/)
- [P2](http://p2theme.com/)
- [a responsive fork of P2 (maybe helpful)](https://github.com/nmec/p2-responsive)
- [WPorg P2](https://meta.svn.wordpress.org/sites/trunk/wordpress.org/public_html/wp-content/themes/pub/wporg-p2/)
- [Rosetta](https://meta.trac.wordpress.org/browser/sites/trunk/global.wordpress.org/public_html/wp-content/themes/rosetta?order=name)
- [WordPress Meta Environment](https://make.wordpress.org/meta/2014/06/23/wordpress-meta-environment/)
## Comments?

Shoot. :)

**Comment by glueckpress** [comment]
Updated description above with a link to the Meta Handbook according to [this comment](https://github.com/deworg/p2-rosetta/issues/2#issuecomment-58114096) by @samuelsidler.

**Comment by glueckpress** [comment]
Thanks to @nacin, https://de.wordpress.org/team/ is already there. Concrete issues regarding CSS contributions (if any) are to follow.

**Comment by HeikoMamerow** [comment]
Aaaaaargh, I wanted to bring it just to an end: https://github.com/HeikoMamerow/p2-rosetta

Wer zu spät kommt... :-)

**Comment by glueckpress** [comment]
@HeikoMamerow Thanks nonetheless! We’re just getting started with community contributions here, so communication might still be a bit chaotic. We’ll get there in the future.

**Comment by glueckpress** [comment]
Since https://de.wordpress.org/team/ exists and flourishes, there is no further need for this project. I’m closing this issue, but will leave the repository in place for documentary purposes.
