### ISSUE TITLE
Need Rosetta theme

### ISSUE THREAD

**Issue by HeikoMamerow** [deworg/p2-rosetta#2]
Where can i find the Rosetta theme for downloading?

**Comment by samuelsidler** [comment]
More information about global.wordpress.org is here: https://make.wordpress.org/meta/handbook/projects/global-wordpress-org/

**Comment by HeikoMamerow** [comment]
Thank you Samuel!

Just for the record: https://meta.svn.wordpress.org/sites/trunk/global.wordpress.org/public_html/wp-content/themes/rosetta/
